# Render production dynamic binding injections
spring.datasource.url=${postgresql://reddy:HpHcYdIg64JS7RD1G8YfPyDRAQkGHc5T@dpg-d92uripkh4rs73956hj0-a/healthbridge_oeob}
spring.datasource.username=${reddy}
spring.datasource.password=${HpHcYdIg64JS7RD1G8YfPyDRAQkGHc5T}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Infrastructure Automation parameters
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security Web Components Signing Configuration
dockerappointment.app.jwtSecret=${JWT_SECRET_KEY}
dockerappointment.app.jwtExpirationMs=86400000